#!/usr/bin/env bash

# os available ?
if [ -f /etc/os-release ]; then
    source /etc/os-release
else
    PRETTY_NAME="Linux"
fi

# Welcome Message
printf "\n%s\n" "$(date)"
printf "%s | %s\n" "$PRETTY_NAME" "$(uname -r)"

# Show Hostname
printf "\033[1;34m"
figlet $(hostname)
printf "\033[0m"

# System Params
load=`cat /proc/loadavg     | awk '{print $2}'`
memory_usage=`free -m       | awk '/Mem/ { printf("%3.1f%%", $3/$2*100) }'`
swap_usage=`free -m         | awk '/Swap/ { printf("%3.1f%%", $3/$2*100) }'`
users=`users                | wc -w`

echo ""
printf "System load:\t%s\tMemory usage:\t%s\n" $load $memory_usage
printf "Local users:\t%s\tSwap usage:\t%s\n" $users $swap_usage
echo ""

# Get disk usage (use 2s timeout for weak nfs mounts)
timeout --signal=kill 2s df -h | grep -E "^(/dev/|Filesystem)"

# empty line
echo ""
